server:
  port: 8080
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      suffix: /
      prefix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/cmfz
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath:com/hujie/mapper/*Mapper.xml
  type-aliases-package: com.hujie.entity